import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execSync } from "node:child_process";
import { join } from "node:path";

const CLI = join(import.meta.dirname, "..", "cli.mjs");

function run(args, opts = {}) {
  try {
    const stdout = execSync(`node ${CLI} ${args}`, {
      encoding: "utf-8",
      timeout: 10000,
      ...opts,
    });
    return { stdout, exitCode: 0 };
  } catch (err) {
    return {
      stdout: err.stdout || "",
      stderr: err.stderr || "",
      exitCode: err.status,
    };
  }
}

// ── CLI Integration Tests ──────────────────────────────────────────────────

describe("CLI argument handling", () => {
  it("exits 2 with usage message when no arguments given", () => {
    const result = run("");
    assert.equal(result.exitCode, 2);
    assert.ok(result.stderr.includes("Usage:"));
  });

  it("exits 2 for invalid YouTube URL", () => {
    const result = run("not-a-valid-url-at-all");
    assert.equal(result.exitCode, 2);
    assert.ok(result.stderr.includes("Invalid YouTube URL or ID"));
  });

  it("exits 2 for empty-like arguments", () => {
    const result = run('""');
    assert.equal(result.exitCode, 2);
  });

  it("correctly parses --timestamps flag without erroring on flag parsing", () => {
    // Should not treat --timestamps as a positional arg
    const result = run("--timestamps");
    assert.equal(result.exitCode, 2, "Should fail with exit 2 (no positional arg)");
    assert.ok(result.stderr.includes("Usage:"));
  });

  it("correctly parses --json flag without erroring on flag parsing", () => {
    const result = run("--json");
    assert.equal(result.exitCode, 2, "Should fail with exit 2 (no positional arg)");
  });
});

describe("CLI extractVideoId integration", () => {
  it("accepts a bare 11-char video ID", () => {
    // This will try to fetch the transcript (may fail with exit 1 if network unavailable)
    // but should NOT exit 2 (invalid input)
    const result = run("dQw4w9WgXcQ --json", { timeout: 30000 });
    assert.notEqual(result.exitCode, 2, "Should not be invalid input");
  });

  it("accepts a full youtube.com URL", () => {
    const result = run('"https://www.youtube.com/watch?v=dQw4w9WgXcQ" --json', { timeout: 30000 });
    assert.notEqual(result.exitCode, 2, "Should not be invalid input");
  });

  it("accepts a youtu.be short URL", () => {
    const result = run('"https://youtu.be/dQw4w9WgXcQ" --json', { timeout: 30000 });
    assert.notEqual(result.exitCode, 2, "Should not be invalid input");
  });
});

describe("CLI output format", () => {
  it("outputs valid JSON when --json flag is used (if transcript available)", () => {
    const result = run("dQw4w9WgXcQ --json", { timeout: 30000 });
    if (result.exitCode === 0) {
      const parsed = JSON.parse(result.stdout);
      assert.ok(parsed.videoId, "JSON should contain videoId");
      assert.ok(parsed.title, "JSON should contain title");
      assert.ok(parsed.method, "JSON should contain method");
      assert.ok(typeof parsed.segmentCount === "number", "JSON should contain segmentCount");
      assert.ok(Array.isArray(parsed.segments), "JSON should contain segments array");
    }
    // If exit 1 (no captions), that is acceptable for this test
  });

  it("outputs markdown by default (if transcript available)", () => {
    const result = run("dQw4w9WgXcQ", { timeout: 30000 });
    if (result.exitCode === 0) {
      assert.ok(result.stdout.startsWith("#"), "Markdown should start with heading");
      assert.ok(result.stdout.includes("---"), "Markdown should contain horizontal rules");
      assert.ok(result.stdout.includes("Generated by FastyTranscript CLI"));
    }
  });

  it("includes timestamps when --timestamps flag is used (if transcript available)", () => {
    const result = run("dQw4w9WgXcQ --timestamps", { timeout: 30000 });
    if (result.exitCode === 0) {
      // Timestamps look like [00:00] or [01:23]
      assert.ok(/\[\d{2}:\d{2}\]/.test(result.stdout), "Should contain timestamp markers");
    }
  });
});
