import { Innertube } from "youtubei.js";

// Function to extract video ID from URL
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([a-zA-Z0-9_-]+)/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]+)/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }
  return null;
}

// Get YouTube transcript using youtubei.js (InnerTube)
export async function getVideoTranscript(
  videoId: string,
): Promise<{ transcript: string; title: string }> {
  try {
    const youtube = await Innertube.create();
    const info = await youtube.getInfo(videoId);
    
    const title = info.basic_info.title || `YouTube Video ${videoId}`;
    
    try {
      const transcriptData = await info.getTranscript();
      
      if (!transcriptData?.transcript?.content?.body?.initial_segments) {
        throw new Error("No transcript segments found");
      }

      const segments = transcriptData.transcript.content.body.initial_segments;
      const transcript = segments
        .map((seg: any) => seg.snippet.text)
        .join(" ");

      return { transcript, title };
    } catch (transcriptError) {
      // Check if it's a "no transcript" error
      const msg = String(transcriptError);
      if (msg.includes("is disabled") || msg.includes("not available")) {
        throw new Error("No transcript available for this video");
      }
      throw transcriptError;
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    if (msg.includes("No transcript")) {
      throw error;
    }
    throw new Error(`Failed to fetch transcript: ${msg}`);
  }
}

// Format transcript as Markdown
export function formatTranscriptAsMarkdown(
  transcript: string,
  videoId: string,
  title: string,
): string {
  return `# ${title}

**URL:** https://youtube.com/watch?v=${videoId}

---

${transcript}

---

*Generated by FastyTranscript*`;
}
