import { YoutubeTranscript } from "@danielxceron/youtube-transcript";

// Extract video ID from various YouTube URL formats
export function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([a-zA-Z0-9_-]+)/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]+)/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]+)/,
    /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]+)/,
    /^([a-zA-Z0-9_-]{11})$/, // Just the video ID
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }
  return null;
}

// Fetch video title using YouTube's oEmbed API (fast, no API key needed)
async function fetchVideoTitle(videoId: string): Promise<string> {
  try {
    const response = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    );
    if (response.ok) {
      const data = (await response.json()) as { title?: string };
      return data.title || `YouTube Video ${videoId}`;
    }
  } catch {
    // Fallback to video ID if title fetch fails
  }
  return `YouTube Video ${videoId}`;
}

// Get YouTube transcript using youtube-transcript package (FAST!)
export async function getVideoTranscript(videoId: string): Promise<{ transcript: string; title: string }> {
  // Fetch title and transcript in parallel for speed
  const [title, transcriptData] = await Promise.all([
    fetchVideoTitle(videoId),
    YoutubeTranscript.fetchTranscript(videoId).catch((error: Error) => {
      const msg = error.message || String(error);
      if (
        msg.includes("disabled") ||
        msg.includes("not available") ||
        msg.includes("Transcript is disabled") ||
        msg.includes("No transcript")
      ) {
        throw new Error("No transcript available for this video. The video may have captions disabled.");
      }
      throw new Error(`Failed to fetch transcript: ${msg}`);
    }),
  ]);

  if (!transcriptData || transcriptData.length === 0) {
    throw new Error("No transcript available for this video. The video may not have captions.");
  }

  // Combine all transcript segments into plain text
  // Clean up HTML entities and extra whitespace
  const transcript = transcriptData
    .map((segment) => segment.text)
    .join(" ")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();

  return { transcript, title };
}

// Format transcript as Markdown
export function formatTranscriptAsMarkdown(transcript: string, videoId: string, title: string): string {
  return `# ${title}

**URL:** https://youtube.com/watch?v=${videoId}

---

${transcript}

---

*Generated by FastyTranscript*`;
}
